# Generated by Django 5.0 on 2024-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepremiere',
            name='Fournisseur',
        ),
        migrations.AlterField(
            model_name='matierepremiere',
            name='Quantite',
            field=models.IntegerField(default=0),
        ),
    ]
