# Generated by Django 5.0 on 2024-01-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_matierepremiere_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
