# Generated by Django 5.0 on 2024-01-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
