# Generated by Django 5.0 on 2024-01-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='Quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
