# Generated by Django 5.0 on 2024-01-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_matierepremiere_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertmatierepremiere',
            name='MatieresTransferes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achat'),
        ),
    ]
